name: SVV CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  validation:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: List Project Structure
        run: ls -R

      - name: Validate Files
        run: |
          echo "Checking required folders..."
          test -d requirements
          test -d z-model
          test -d vdm-spec
          test -d alloy-model
          test -d validation

      - name: Success Message
        run: echo "SVV Pipeline Validation Passed"
