name: SVV Validation Pipeline

on:
  push:
    branches: [ main ]

jobs:
  check-project:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Verify Project Structure
        run: |
          echo "Checking folders..."
          if [ ! -d "requirements" ]; then exit 1; fi
          if [ ! -d "z-model" ]; then exit 1; fi
          if [ ! -d "vdm-spec" ]; then exit 1; fi
          if [ ! -d "alloy-model" ]; then exit 1; fi
          if [ ! -d "validation" ]; then exit 1; fi
          echo "All required folders exist"

      - name: Success
        run: echo "SVV CI Pipeline Passed"
